/*
 * Copyright (c) 2018 Wave Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pl.wavesoftware.eid.api;

/**
 * An Eid object factory
 *
 * @author <a href="mailto:krzysztof.suszynski@wavesoftware.pl">Krzysztof Suszynski</a>
 * @since 2.0.0
 */
public interface EidFactory {
    /**
     * Constructs a single value of exception ID.
     *
     * @param id the exception id, should be uniquely generated by developer
     * @return a created Eid object
     */
    Eid create(CharSequence id);

    /**
     * Constructs with two values an exception ID and reference of some sort.
     * The second reference can be used to hold reference from external system.
     *
     * @param id  the exception id, should be uniquely generated by developer
     * @param ref a reference from external system
     * @return a created Eid object
     */
    Eid create(CharSequence id, CharSequence ref);
}
